<?php
/**
 * Implements hook_page_attachments_alter().
 */
// function react_components_page_attachments_alter(array &$attachments) {
//   // Debug what libraries are attached
//   if (isset($attachments['#attached']['library'])) {
//     \Drupal::logger('react_components')->notice('Libraries attached: @libs', [
//       '@libs' => implode(', ', $attachments['#attached']['library'])
//     ]);
//   }
// }

function react_components_theme($existing, $type, $theme, $path) {
  $module_path = \Drupal::service('extension.list.module')->getPath('react_components');

  return [
    'react_block' => [
      'render element' => 'content',
      'template' => 'react-block', // Maps to your-custom-block.html.twig
      'path' => $module_path . '/templates',
      'variables' => [
        'uuid' => '',
      ],
    ],
    'paragraph__react_component' => [
      'render element' => 'elements',
      'path' => $module_path . '/templates',
      'template' => 'paragraph--react-component',
    ],
  ];
}

function react_components_preprocess_paragraph__react_component(array &$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  $uuid = $paragraph->uuid();

  $settingsKey = 'rc-paragraph-' . $uuid;

  $variables['#attached']['drupalSettings']['reactComponents'][$settingsKey] = [
    'paragraph_uuid' => $uuid,
    'componentType' => $paragraph->get('field_component_type')->value,
    'title' => $paragraph->get('field_component_title')->value
  ];

  $variables['uuid'] = $uuid;

  // $variables['#attached']['library'][] = ['react_components/react-components-lib'];
}

// let's give the block a custom id based on the title
function react_components_preprocess_block(&$variables) {
  $plugin_id = $variables['elements']['#plugin_id'];

  if ($plugin_id == 'react_block') {

    if (!empty($variables['configuration']['component_title'])) {
      $title = $variables['configuration']['component_title'];
      $id = strtolower($title);
      $id = trim($id);
      $id = preg_replace('/[^a-z0-9]+/', '-', $id);
      $id = 'rcb-' . $id;
      $variables['attributes']['id']  = $id;
    }
  }
}

function react_components_preprocess_page(&$variables) { 
  // for some reason this is the only thing that gets around bigpipe for me right now
  $variables['#attached']['library'][] = 'react_components/react-components-lib';
}
